name: Python Checks

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  quality-checks:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 mypy black isort
        pip install -r requirements.txt
        
    - name: Check formatting with Black
      run: black . --check
        
    - name: Check import sorting with isort
      run: isort . --check-only --profile black
        
    - name: Lint with flake8
      run: flake8 . --max-line-length=88 --extend-ignore=E203
        
    - name: Type checking with mypy
      run: mypy . 